### ISSUE TITLE
version check failed, integration not usable

### ISSUE THREAD

**Issue by Schmandre** [csuermann/virtual-smart-home#23]
Hello,

since today I have the problem, that inside the nodes there is a message "version check failed". If I try to use a voice command, Ill get the error message, that the device is offline.

![image](https://github.com/csuermann/virtual-smart-home/assets/47451170/1b744c7d-8a39-4ca3-87f4-1bc5f19ffb55)

If I check my subscription, I can see that the connections is on "PRO-Plan" so there must be a working connection to check that. 

![image](https://github.com/csuermann/virtual-smart-home/assets/47451170/f22ce83d-11f7-4cf7-bdc1-ffecb11c275f)

Log shows

```
homeassistant_node-red  | AxiosError: getaddrinfo EAI_AGAIN kfd5m4a21f.execute-api.eu-west-1.amazonaws.com
homeassistant_node-red  |     at Function.AxiosError.from (/data/node_modules/axios/dist/node/axios.cjs:837:14)
homeassistant_node-red  |     at RedirectableRequest.handleRequestError (/data/node_modules/axios/dist/node/axios.cjs:3090:25)
homeassistant_node-red  |     at RedirectableRequest.emit (node:events:513:28)
homeassistant_node-red  |     at ClientRequest.eventHandlers.<computed> (/data/node_modules/follow-redirects/index.js:38:24)
homeassistant_node-red  |     at ClientRequest.emit (node:events:513:28)
homeassistant_node-red  |     at TLSSocket.socketErrorListener (node:_http_client:494:9)
homeassistant_node-red  |     at TLSSocket.emit (node:events:513:28)
homeassistant_node-red  |     at emitErrorNT (node:internal/streams/destroy:157:8)
homeassistant_node-red  |     at emitErrorCloseNT (node:internal/streams/destroy:122:3)
homeassistant_node-red  |     at processTicksAndRejections (node:internal/process/task_queues:83:21) {
homeassistant_node-red  |   hostname: 'kfd5m4a21f.execute-api.eu-west-1.amazonaws.com',
homeassistant_node-red  |   syscall: 'getaddrinfo',
homeassistant_node-red  |   code: 'EAI_AGAIN',
homeassistant_node-red  |   errno: -3001,
homeassistant_node-red  |   config: {
homeassistant_node-red  |     transitional: {
homeassistant_node-red  |       silentJSONParsing: true,
homeassistant_node-red  |       forcedJSONParsing: true,
homeassistant_node-red  |       clarifyTimeoutError: false
homeassistant_node-red  |     },
homeassistant_node-red  |     adapter: [ 'xhr', 'http' ],
homeassistant_node-red  |     transformRequest: [ [Function: transformRequest] ],
homeassistant_node-red  |     transformResponse: [ [Function: transformResponse] ],
homeassistant_node-red  |     timeout: 0,
homeassistant_node-red  |     xsrfCookieName: 'XSRF-TOKEN',
homeassistant_node-red  |     xsrfHeaderName: 'X-XSRF-TOKEN',
homeassistant_node-red  |     maxContentLength: -1,
homeassistant_node-red  |     maxBodyLength: -1,
homeassistant_node-red  |     env: { FormData: [Function], Blob: null },
homeassistant_node-red  |     validateStatus: [Function: validateStatus],
homeassistant_node-red  |     headers: Object [AxiosHeaders] {
homeassistant_node-red  |       Accept: 'application/json, text/plain, */*',
homeassistant_node-red  |       'Content-Type': undefined,
homeassistant_node-red  |       'User-Agent': 'axios/1.6.5',
homeassistant_node-red  |       'Accept-Encoding': 'gzip, compress, deflate, br'
homeassistant_node-red  |     },
homeassistant_node-red  |     method: 'get',
homeassistant_node-red  |     url: 'https://kfd5m4a21f.execute-api.eu-west-1.amazonaws.com/dev/check_version?version=4.1.5&nr_version=3.1.7&thingId=vsht-84210ba4-207c-4c60-bd37-59be253f9f62',
homeassistant_node-red  |     data: undefined
homeassistant_node-red  |   },
homeassistant_node-red  |   request: <ref *1> Writable {
homeassistant_node-red  |     _writableState: WritableState {
homeassistant_node-red  |       objectMode: false,
homeassistant_node-red  |       highWaterMark: 16384,
homeassistant_node-red  |       finalCalled: false,
homeassistant_node-red  |       needDrain: false,
homeassistant_node-red  |       ending: false,
homeassistant_node-red  |       ended: false,
homeassistant_node-red  |       finished: false,
homeassistant_node-red  |       destroyed: false,
homeassistant_node-red  |       decodeStrings: true,
homeassistant_node-red  |       defaultEncoding: 'utf8',
homeassistant_node-red  |       length: 0,
homeassistant_node-red  |       writing: false,
homeassistant_node-red  |       corked: 0,
homeassistant_node-red  |       sync: true,
homeassistant_node-red  |       bufferProcessing: false,
homeassistant_node-red  |       onwrite: [Function: bound onwrite],
homeassistant_node-red  |       writecb: null,
homeassistant_node-red  |       writelen: 0,
homeassistant_node-red  |       afterWriteTickInfo: null,
homeassistant_node-red  |       buffered: [],
homeassistant_node-red  |       bufferedIndex: 0,
homeassistant_node-red  |       allBuffers: true,
homeassistant_node-red  |       allNoop: true,
homeassistant_node-red  |       pendingcb: 0,
homeassistant_node-red  |       constructed: true,
homeassistant_node-red  |       prefinished: false,
homeassistant_node-red  |       errorEmitted: false,
homeassistant_node-red  |       emitClose: true,
homeassistant_node-red  |       autoDestroy: true,
homeassistant_node-red  |       errored: null,
homeassistant_node-red  |       closed: false,
homeassistant_node-red  |       closeEmitted: false,
homeassistant_node-red  |       [Symbol(kOnFinished)]: []
homeassistant_node-red  |     },
homeassistant_node-red  |     _events: [Object: null prototype] {
homeassistant_node-red  |       response: [Function: handleResponse],
homeassistant_node-red  |       error: [Function: handleRequestError],
homeassistant_node-red  |       socket: [Function: handleRequestSocket]
homeassistant_node-red  |     },
homeassistant_node-red  |     _eventsCount: 3,
homeassistant_node-red  |     _maxListeners: undefined,
homeassistant_node-red  |     _options: {
homeassistant_node-red  |       maxRedirects: 21,
homeassistant_node-red  |       maxBodyLength: Infinity,
homeassistant_node-red  |       protocol: 'https:',
homeassistant_node-red  |       path: '/dev/check_version?version=4.1.5&nr_version=3.1.7&thingId=vsht-84210ba4-207c-4c60-bd37-59be253f9f62',
homeassistant_node-red  |       method: 'GET',
homeassistant_node-red  |       headers: [Object: null prototype],
homeassistant_node-red  |       agents: [Object],
homeassistant_node-red  |       auth: undefined,
homeassistant_node-red  |       family: undefined,
homeassistant_node-red  |       beforeRedirect: [Function: dispatchBeforeRedirect],
homeassistant_node-red  |       beforeRedirects: [Object],
homeassistant_node-red  |       hostname: 'kfd5m4a21f.execute-api.eu-west-1.amazonaws.com',
homeassistant_node-red  |       port: '',
homeassistant_node-red  |       agent: undefined,
homeassistant_node-red  |       nativeProtocols: [Object],
homeassistant_node-red  |       pathname: '/dev/check_version',
homeassistant_node-red  |       search: '?version=4.1.5&nr_version=3.1.7&thingId=vsht-84210ba4-207c-4c60-bd37-59be253f9f62'
homeassistant_node-red  |     },
homeassistant_node-red  |     _ended: true,
homeassistant_node-red  |     _ending: true,
homeassistant_node-red  |     _redirectCount: 0,
homeassistant_node-red  |     _redirects: [],
homeassistant_node-red  |     _requestBodyLength: 0,
homeassistant_node-red  |     _requestBodyBuffers: [],
homeassistant_node-red  |     _onNativeResponse: [Function (anonymous)],
homeassistant_node-red  |     _currentRequest: ClientRequest {
homeassistant_node-red  |       _events: [Object: null prototype],
homeassistant_node-red  |       _eventsCount: 7,
homeassistant_node-red  |       _maxListeners: undefined,
homeassistant_node-red  |       outputData: [],
homeassistant_node-red  |       outputSize: 0,
homeassistant_node-red  |       writable: true,
homeassistant_node-red  |       destroyed: false,
homeassistant_node-red  |       _last: true,
homeassistant_node-red  |       chunkedEncoding: false,
homeassistant_node-red  |       shouldKeepAlive: false,
homeassistant_node-red  |       maxRequestsOnConnectionReached: false,
homeassistant_node-red  |       _defaultKeepAlive: true,
homeassistant_node-red  |       useChunkedEncodingByDefault: false,
homeassistant_node-red  |       sendDate: false,
homeassistant_node-red  |       _removedConnection: false,
homeassistant_node-red  |       _removedContLen: false,
homeassistant_node-red  |       _removedTE: false,
homeassistant_node-red  |       strictContentLength: false,
homeassistant_node-red  |       _contentLength: 0,
homeassistant_node-red  |       _hasBody: true,
homeassistant_node-red  |       _trailer: '',
homeassistant_node-red  |       finished: true,
homeassistant_node-red  |       _headerSent: true,
homeassistant_node-red  |       _closed: false,
homeassistant_node-red  |       socket: [TLSSocket],
homeassistant_node-red  |       _header: 'GET /dev/check_version?version=4.1.5&nr_version=3.1.7&thingId=vsht-84210ba4-207c-4c60-bd37-59be253f9f62 HTTP/1.1\r\n' +
homeassistant_node-red  |         'Accept: application/json, text/plain, */*\r\n' +
homeassistant_node-red  |         'User-Agent: axios/1.6.5\r\n' +
homeassistant_node-red  |         'Accept-Encoding: gzip, compress, deflate, br\r\n' +
homeassistant_node-red  |         'Host: kfd5m4a21f.execute-api.eu-west-1.amazonaws.com\r\n' +
homeassistant_node-red  |         'Connection: close\r\n' +
homeassistant_node-red  |         '\r\n',
homeassistant_node-red  |       _keepAliveTimeout: 0,
homeassistant_node-red  |       _onPendingData: [Function: nop],
homeassistant_node-red  |       agent: [Agent],
homeassistant_node-red  |       socketPath: undefined,
homeassistant_node-red  |       method: 'GET',
homeassistant_node-red  |       maxHeaderSize: undefined,
homeassistant_node-red  |       insecureHTTPParser: undefined,
homeassistant_node-red  |       path: '/dev/check_version?version=4.1.5&nr_version=3.1.7&thingId=vsht-84210ba4-207c-4c60-bd37-59be253f9f62',
homeassistant_node-red  |       _ended: false,
homeassistant_node-red  |       res: null,
homeassistant_node-red  |       aborted: false,
homeassistant_node-red  |       timeoutCb: null,
homeassistant_node-red  |       upgradeOrConnect: false,
homeassistant_node-red  |       parser: null,
homeassistant_node-red  |       maxHeadersCount: null,
homeassistant_node-red  |       reusedSocket: false,
homeassistant_node-red  |       host: 'kfd5m4a21f.execute-api.eu-west-1.amazonaws.com',
homeassistant_node-red  |       protocol: 'https:',
homeassistant_node-red  |       _redirectable: [Circular *1],
homeassistant_node-red  |       [Symbol(kCapture)]: false,
homeassistant_node-red  |       [Symbol(kBytesWritten)]: 0,
homeassistant_node-red  |       [Symbol(kEndCalled)]: true,
homeassistant_node-red  |       [Symbol(kNeedDrain)]: false,
homeassistant_node-red  |       [Symbol(corked)]: 0,
homeassistant_node-red  |       [Symbol(kOutHeaders)]: [Object: null prototype],
homeassistant_node-red  |       [Symbol(kUniqueHeaders)]: null
homeassistant_node-red  |     },
homeassistant_node-red  |     _currentUrl: 'https://kfd5m4a21f.execute-api.eu-west-1.amazonaws.com/dev/check_version?version=4.1.5&nr_version=3.1.7&thingId=vsht-84210ba4-207c-4c60-bd37-59be253f9f62',
homeassistant_node-red  |     [Symbol(kCapture)]: false
homeassistant_node-red  |   },
homeassistant_node-red  |   cause: Error: getaddrinfo EAI_AGAIN kfd5m4a21f.execute-api.eu-west-1.amazonaws.com
homeassistant_node-red  |       at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:109:26) {
homeassistant_node-red  |     errno: -3001,
homeassistant_node-red  |     code: 'EAI_AGAIN',
homeassistant_node-red  |     syscall: 'getaddrinfo',
homeassistant_node-red  |     hostname: 'kfd5m4a21f.execute-api.eu-west-1.amazonaws.com'
homeassistant_node-red  |   }
homeassistant_node-red  | }
homeassistant_node-red  | 21 Mar 06:48:49 - [error] [http request:5ba81317a155e02a-60ef6611d23b123d] RequestError: getaddrinfo EAI_AGAIN app.divera247.com
homeassistant_node-red  | 21 Mar 06:48:49 - [error] [function:build request message] TypeError: Cannot read properties of null (reading '1')
```

A small edit. Is just tried a fresh docker install of node red and tried to install v 4.2 directly. I got the error, that the URL ```https://registry.npmjs.org/node-red-contrib-virtual-smart-home failed, reason: getaddrinfo EAI_AGAIN registry.npmjs.org```is not reachable.

If I ping it from docker host, working. If I try to open inside network, working. Any ideas how to fix?

**Comment by csuermann** [comment]
Hi @Schmandre!

The EAI_AGAIN error typically indicates a DNS lookup timeout, which often points to network connectivity or proxy-related issues. Given that you're encountering this error for domains unrelated to VSH, it suggests there might be a broader issue with your setup.

Additionally, I'd like to note that the information about the PRO plan is sourced from MQTT messages originating from the VSH backend, utilizing a different port and protocol than the version check, which operates over HTTP. Perhaps this information might be helpful for troubleshooting.
