### ISSUE TITLE
Issues after being down for a couple months.

### ISSUE THREAD

**Issue by turbo2ltr** [csuermann/virtual-smart-home#27]
I'm running version 2.0.3 in a node red docker container with my own AWS back end and everything was working fine when I moved.
I'm set up in the new house and I'm trying to figure out why alexa commands to virtual devices are not working. 
In NodeRed, I get "user not found! Is VSH skill enabled?" next to virtual devices. I went checked everything and not seeing any issues. 

The virtual devices show up in my alexa app, but says "server is unresponsive".

In the VSH AWS IoT thing I'm seeing Connected, Subscribed, Shadow Updated, Disconnect messages when I restart the flow. But no further messages appear. 
If I refresh the token in the connection setup in NodeRed, it seems to update just fine. All my registered devices are there.

I went through my VSH Skill settings in the Developer console and all seems fine.

So I'm really confused why it stopped working or exactly what "user" it is talking about.  Essentially I unplugged it from one house and plugged it into another, but clearly something broke.

Also I'm unclear what this "momento" thing is that is required. I don't recall ever doing that.

Really don't have the time to do a full node red upgrade required to run the latest version of VSH.  The rabbit hole is already way deeper than I was prepared for for today.

**Comment by turbo2ltr** [comment]
Just some additional info.
I tested the skill using the test tab in the alexa console and it failed with "Endpoint unreachable"
The Default and North American endpoint I have int he skill is: `arn:aws:lambda:us-east-1:XXXXXXXXXX:function:virtual-smart-home-dev-skill`
This is the same ARN displayed in AWS ->Lambda -> Functions ->virtual-smart-home-dev-skill

I downloaded the SAM for that function
In there, it is pointing to IOT endpoint `a2XXXXXXXXy-ats.iot.us-east-1.amazonaws.com`
This is the same endpoint returned when I run the CLI command `aws iot describe-endpoint --endpoint-type iot:Data-ATS`

The alexa client ID and Secret are the same as in the "Permissions" tab of the Alexa skill.

I just don't know where the breakdown is.

**Comment by turbo2ltr** [comment]
So I took the plunge and updated _everything_.
Now it doesn't work at all. lol.
```
30 Jun 18:59:44 - [info] [vsh-connection:{my amazon email address}] MQTT: publish to topic vsh/vsht-ff9aed9e-6961-4f5a-a163-XXXXXXXX/requestConfig: {"vshVersion":"4.4.1"}
30 Jun 18:59:45 - [info] [vsh-connection:{my amazon email address}] MQTT: message received on topic vsh/vsht-ff9aed9e-6961-4f5a-a163-XXXXXXX/service: {"operation":"kill","reason":"User not found! VSH Alexa skill enabled?"}
30 Jun 18:59:45 - [red] Uncaught Exception:
30 Jun 18:59:45 - [error] TypeError: this[logLevel] is not a function
    at ConnectionNode.logger (/data/node_modules/node-red-contrib-virtual-smart-home/connection.js:70:27)
    at ConnectionNode.handleKill (/data/node_modules/node-red-contrib-virtual-smart-home/connection.js:610:12)
    at ConnectionNode.handleService (/data/node_modules/node-red-contrib-virtual-smart-home/connection.js:644:16)
    at MqttClient.<anonymous> (/data/node_modules/node-red-contrib-virtual-smart-home/connection.js:823:18)
    at MqttClient.emit (node:events:519:28)
    at MqttClient.<anonymous> (/data/node_modules/node-red-contrib-virtual-smart-home/MqttClient.js:52:12)
    at MqttClient.emit (node:events:519:28)
    at Array.<anonymous> (/data/node_modules/node-red-contrib-virtual-smart-home/node_modules/mqtt/build/lib/handlers/publish.js:85:28)
    at MqttClient.options.customHandleAcks (/data/node_modules/node-red-contrib-virtual-smart-home/node_modules/mqtt/build/lib/client.js:94:28)
    at handlePublish (/data/node_modules/node-red-contrib-virtual-smart-home/node_modules/mqtt/build/lib/handlers/publish.js:73:21)
```

**Comment by csuermann** [comment]
Hi @turbo2ltr,

Have you checked your DynamoDB table? My hunch is that your user record got auto-deleted after inactivity. You should be able to fix this by just creating a new VSH-connection. Make sure you [configure](https://github.com/csuermann/virtual-smart-home?tab=readme-ov-file#configuring-node-red) your Node-RED instance to (again) use your own backend.

Hope that helps.

Best,
Cornelius

**Comment by turbo2ltr** [comment]
Ahh dang, I should have waited before I blew everything away.  I did look at the Dynamo DB, but I also didn't know what should be in there. All I saw was my  devices which seemed like it was working.
Is it easy enough to add manually? i.e. is it just a key with my amazon username?

**Comment by csuermann** [comment]
You'd have to know your Amazon User ID, so I guess manually recreating the record wouldn't work. But creating a new VSH-connection as I pointed out should do the trick.

**Comment by turbo2ltr** [comment]
I went into the flows.json and removed the "type: vsh-connection" block so NR would boot.
In the VSH nodes, there was no more connection, so I added a new connection.  I entered the  logged into my account and used the code to sync..
When I returned to NR, I get the same error but in a nice red box.
![image](https://github.com/csuermann/virtual-smart-home/assets/10290656/029e597d-47ca-4cd3-b3c4-3fbabacb2e2b)
 
Do I need to delete the account in a different way?

**Comment by csuermann** [comment]
Are you sure your Node-RED is talking to _your_ backend and not mine? After going through the account linking process, there should be a TOKEN record in the VSH DynamoDB table.

**Comment by csuermann** [comment]
Indeed, the VSH backend was never optimized for self-hosting and setting it up is not straight forward. Perhaps you want to consider using the official VSH backend?! ;-)
