### ISSUE TITLE
Error in step 20: serverless deploy

### ISSUE THREAD

**Issue by Pesach85** [csuermann/virtual-smart-home#3]
This is the log of my error:

C:\virtual-smart-home>serverless deploy
Serverless: To ensure safe major version upgrades ensure "frameworkVersion" setting in service configuration (recommended setup: "frameworkVersion: ^2.66.1")

Serverless: Load command interactiveCli
Serverless: Load command config
Serverless: Load command config:credentials
Serverless: Load command config:tabcompletion
Serverless: Load command config:tabcompletion:install
Serverless: Load command config:tabcompletion:uninstall
Serverless: Load command create
Serverless: Load command install
Serverless: Load command package
Serverless: Load command deploy
Serverless: Load command deploy:function
Serverless: Load command deploy:list
Serverless: Load command deploy:list:functions
Serverless: Load command invoke
Serverless: Load command invoke:local
Serverless: Load command info
Serverless: Load command logs
Serverless: Load command metrics
Serverless: Load command print
Serverless: Load command remove
Serverless: Load command rollback
Serverless: Load command rollback:function
Serverless: Load command slstats
Serverless: Load command plugin
Serverless: Load command plugin
Serverless: Load command plugin:install
Serverless: Load command plugin
Serverless: Load command plugin:uninstall
Serverless: Load command plugin
Serverless: Load command plugin:list
Serverless: Load command plugin
Serverless: Load command plugin:search
Serverless: Load command config
Serverless: Load command config:credentials
Serverless: Load command upgrade
Serverless: Load command uninstall
Serverless: Load command webpack
Serverless: Load command login
Serverless: Load command logout
Serverless: Load command generate-event
Serverless: Load command test
Serverless: Load command dashboard
Serverless: Load command output
Serverless: Load command output:get
Serverless: Load command output:list
Serverless: Load command param
Serverless: Load command param:get
Serverless: Load command param:list
Serverless: Load command studio
Serverless: Skipping variables resolution with old resolver (new resolver reported no more variables to resolve)
Serverless: Configuration warning:
Serverless:   at 'functions.skill': unrecognized property 'regions'
Serverless:   at 'functions.backchannel': unrecognized property 'regions'
Serverless:   at 'functions.cleanup': unrecognized property 'regions'
Serverless:   at 'functions.provision': unrecognized property 'regions'
Serverless:   at 'functions.admin': unrecognized property 'regions'
Serverless:
Serverless: Learn more about configuration validation here: http://slss.io/configuration-validation
Serverless:
Serverless: Invoke deploy
Serverless: Invoke package
Serverless: Invoke aws:common:validate
Serverless: Invoke aws:common:cleanupTempDir
Serverless: Select: selecting functions for deployment
Serverless: Invoke webpack:validate
Serverless: Invoke webpack:compile
Serverless: Bundling with Webpack...
Time: 1066ms
Built at: 12/11/2021 10:40:35
           Asset      Size  Chunks         Chunk Names
        admin.js  1.32 KiB       0         admin
    admin.js.map  4.53 KiB       0  [dev]  admin
      cleanup.js  1.32 KiB       1         cleanup
  cleanup.js.map  4.53 KiB       1  [dev]  cleanup
      handler.js  1.32 KiB       2         handler
  handler.js.map  4.53 KiB       2  [dev]  handler
    provision.js  1.32 KiB       3         provision
provision.js.map  4.53 KiB       3  [dev]  provision
Entrypoint handler = handler.js handler.js.map
Entrypoint cleanup = cleanup.js cleanup.js.map
Entrypoint provision = provision.js provision.js.map
Entrypoint admin = admin.js admin.js.map
[0] ./handler.ts 327 bytes {2} [built] [failed] [1 error]
[1] ./cleanup.ts 327 bytes {1} [built] [failed] [1 error]
[2] ./provision.ts 327 bytes {3} [built] [failed] [1 error]
[3] ./admin.ts 327 bytes {0} [built] [failed] [1 error]

ERROR in ./handler.ts
Module build failed (from ./node_modules/ts-loader/index.js):
TypeError: loaderContext.getOptions is not a function
    at getLoaderOptions (C:\virtual-smart-home\node_modules\ts-loader\dist\index.js:91:41)
    at Object.loader (C:\virtual-smart-home\node_modules\ts-loader\dist\index.js:14:21)

ERROR in ./admin.ts
Module build failed (from ./node_modules/ts-loader/index.js):
TypeError: loaderContext.getOptions is not a function
    at getLoaderOptions (C:\virtual-smart-home\node_modules\ts-loader\dist\index.js:91:41)
    at Object.loader (C:\virtual-smart-home\node_modules\ts-loader\dist\index.js:14:21)

ERROR in ./provision.ts
Module build failed (from ./node_modules/ts-loader/index.js):
TypeError: loaderContext.getOptions is not a function
    at getLoaderOptions (C:\virtual-smart-home\node_modules\ts-loader\dist\index.js:91:41)
    at Object.loader (C:\virtual-smart-home\node_modules\ts-loader\dist\index.js:14:21)

ERROR in ./cleanup.ts
Module build failed (from ./node_modules/ts-loader/index.js):
TypeError: loaderContext.getOptions is not a function
    at getLoaderOptions (C:\virtual-smart-home\node_modules\ts-loader\dist\index.js:91:41)
    at Object.loader (C:\virtual-smart-home\node_modules\ts-loader\dist\index.js:14:21)
Serverless: [AWS sts 200 1.831s 0 retries] getCallerIdentity({})

 Error ---------------------------------------------------

  Error: Webpack compilation error, see stats above
      at C:\virtual-smart-home\node_modules\serverless-webpack\lib\compile.js:96:15
      at arrayEach (C:\virtual-smart-home\node_modules\lodash\lodash.js:530:11)
      at Function.forEach (C:\virtual-smart-home\node_modules\lodash\lodash.js:9410:14)
      at C:\virtual-smart-home\node_modules\serverless-webpack\lib\compile.js:93:7
      at tryCatcher (C:\virtual-smart-home\node_modules\bluebird\js\release\util.js:16:23)
      at Promise._settlePromiseFromHandler (C:\virtual-smart-home\node_modules\bluebird\js\release\promise.js:547:31)
      at Promise._settlePromise (C:\virtual-smart-home\node_modules\bluebird\js\release\promise.js:604:18)
      at Promise._settlePromise0 (C:\virtual-smart-home\node_modules\bluebird\js\release\promise.js:649:10)
      at Promise._settlePromises (C:\virtual-smart-home\node_modules\bluebird\js\release\promise.js:729:18)
      at Promise._fulfill (C:\virtual-smart-home\node_modules\bluebird\js\release\promise.js:673:18)
      at C:\virtual-smart-home\node_modules\bluebird\js\release\nodeback.js:42:21
      at finalCallback (C:\virtual-smart-home\node_modules\webpack\lib\Compiler.js:257:39)
      at C:\virtual-smart-home\node_modules\webpack\lib\Compiler.js:273:13
      at AsyncSeriesHook.eval [as callAsync] (eval at create (C:\virtual-smart-home\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:6:1)
      at AsyncSeriesHook.lazyCompileHook (C:\virtual-smart-home\node_modules\tapable\lib\Hook.js:154:20)
      at onCompiled (C:\virtual-smart-home\node_modules\webpack\lib\Compiler.js:271:21)
      at C:\virtual-smart-home\node_modules\webpack\lib\Compiler.js:681:15
      at AsyncSeriesHook.eval [as callAsync] (eval at create (C:\virtual-smart-home\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:6:1)
      at AsyncSeriesHook.lazyCompileHook (C:\virtual-smart-home\node_modules\tapable\lib\Hook.js:154:20)
      at C:\virtual-smart-home\node_modules\webpack\lib\Compiler.js:678:31
      at AsyncSeriesHook.eval [as callAsync] (eval at create (C:\virtual-smart-home\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:6:1)
      at AsyncSeriesHook.lazyCompileHook (C:\virtual-smart-home\node_modules\tapable\lib\Hook.js:154:20)
      at C:\virtual-smart-home\node_modules\webpack\lib\Compilation.js:1423:35
      at AsyncSeriesHook.eval [as callAsync] (eval at create (C:\virtual-smart-home\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:6:1)
      at AsyncSeriesHook.lazyCompileHook (C:\virtual-smart-home\node_modules\tapable\lib\Hook.js:154:20)
      at C:\virtual-smart-home\node_modules\webpack\lib\Compilation.js:1414:32
      at eval (eval at create (C:\virtual-smart-home\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:11:1)
      at C:\virtual-smart-home\node_modules\terser-webpack-plugin\dist\index.js:321:9
      at step (C:\virtual-smart-home\node_modules\terser-webpack-plugin\dist\TaskRunner.js:87:9)
      at done (C:\virtual-smart-home\node_modules\terser-webpack-plugin\dist\TaskRunner.js:98:30)
      at tryCatcher (C:\virtual-smart-home\node_modules\bluebird\js\release\util.js:16:23)
      at Promise._settlePromiseFromHandler (C:\virtual-smart-home\node_modules\bluebird\js\release\promise.js:547:31)
      at Promise._settlePromise (C:\virtual-smart-home\node_modules\bluebird\js\release\promise.js:604:18)
      at Promise._settlePromise0 (C:\virtual-smart-home\node_modules\bluebird\js\release\promise.js:649:10)
      at Promise._settlePromises (C:\virtual-smart-home\node_modules\bluebird\js\release\promise.js:729:18)
      at Promise._fulfill (C:\virtual-smart-home\node_modules\bluebird\js\release\promise.js:673:18)
      at Promise._resolveCallback (C:\virtual-smart-home\node_modules\bluebird\js\release\promise.js:466:57)
      at Promise._settlePromiseFromHandler (C:\virtual-smart-home\node_modules\bluebird\js\release\promise.js:559:17)
      at Promise._settlePromise (C:\virtual-smart-home\node_modules\bluebird\js\release\promise.js:604:18)
      at Promise._settlePromise0 (C:\virtual-smart-home\node_modules\bluebird\js\release\promise.js:649:10)
      at Promise._settlePromises (C:\virtual-smart-home\node_modules\bluebird\js\release\promise.js:729:18)
      at Promise._fulfill (C:\virtual-smart-home\node_modules\bluebird\js\release\promise.js:673:18)
      at Promise._resolveCallback (C:\virtual-smart-home\node_modules\bluebird\js\release\promise.js:466:57)
      at Promise._settlePromiseFromHandler (C:\virtual-smart-home\node_modules\bluebird\js\release\promise.js:559:17)
      at Promise._settlePromise (C:\virtual-smart-home\node_modules\bluebird\js\release\promise.js:604:18)
      at Promise._settlePromise0 (C:\virtual-smart-home\node_modules\bluebird\js\release\promise.js:649:10)
      at Promise._settlePromises (C:\virtual-smart-home\node_modules\bluebird\js\release\promise.js:729:18)
      at Promise._fulfill (C:\virtual-smart-home\node_modules\bluebird\js\release\promise.js:673:18)
      at Promise._settlePromise (C:\virtual-smart-home\node_modules\bluebird\js\release\promise.js:617:21)
      at Promise._settlePromise0 (C:\virtual-smart-home\node_modules\bluebird\js\release\promise.js:649:10)
      at Promise._settlePromises (C:\virtual-smart-home\node_modules\bluebird\js\release\promise.js:729:18)
      at Promise._fulfill (C:\virtual-smart-home\node_modules\bluebird\js\release\promise.js:673:18)
      at Promise._resolveCallback (C:\virtual-smart-home\node_modules\bluebird\js\release\promise.js:489:14)
      at Promise._settlePromiseFromHandler (C:\virtual-smart-home\node_modules\bluebird\js\release\promise.js:559:17)
      at Promise._settlePromise (C:\virtual-smart-home\node_modules\bluebird\js\release\promise.js:604:18)
      at Promise._settlePromise0 (C:\virtual-smart-home\node_modules\bluebird\js\release\promise.js:649:10)
      at Promise._settlePromises (C:\virtual-smart-home\node_modules\bluebird\js\release\promise.js:729:18)
      at Promise._fulfill (C:\virtual-smart-home\node_modules\bluebird\js\release\promise.js:673:18)
      at C:\virtual-smart-home\node_modules\bluebird\js\release\nodeback.js:42:21
      at C:\virtual-smart-home\node_modules\graceful-fs\graceful-fs.js:166:16
      at C:\Program Files\nodejs\node_modules\serverless\node_modules\graceful-fs\graceful-fs.js:164:16
      at C:\Program Files\nodejs\node_modules\serverless\node_modules\graceful-fs\graceful-fs.js:143:16
      at C:\Program Files\nodejs\node_modules\serverless\node_modules\graceful-fs\graceful-fs.js:61:14
      at FSReqCallback.oncomplete (node:fs:188:23)

  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com

  Your Environment Information ---------------------------
     Operating System:          win32
     Node Version:              16.13.0
     Framework Version:         2.66.1
     Plugin Version:            5.5.1
     SDK Version:               4.3.0
     Components Version:        3.18.0

Serverless: Deprecation warning: Resolution of lambda version hashes was improved with better algorithm, which will be used in next major release.
            Switch to it now by setting "provider.lambdaHashingVersion" to "20201221".
            While it is highly encouraged to upgrade to new algorithm, you can still use the old approach by setting "provider.lambdaHashingVersion" to "20200924".
            More Info: https://www.serverless.com/framework/docs/deprecations/#LAMBDA_HASHING_VERSION_V2

**Comment by Pesach85** [comment]
I reply to myself after a research, this solves all, dependency issues on ts-loader, 
npm install -g ts-loader@8.3.0

 https://github.com/TypeStrong/ts-loader/issues/595
